sudo: required
services:
  - docker

before_install:
  - docker build -t tim/docker-react .


script:
  - docker run tim/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend---------------"
  env: "Frontend---------------env"
  bucket_name: "elasticbeanstalk-us-east-2-891377328480"
  bucket_path:  "frontend---------------"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"