sudo: required
services:
  - docker

before_install:
  - docker build -t tim/docker-react -f dockerfile.dev .


script:
  - docker run -e CI=true tim/docker-react npm run test 

deploy:
  provider:elasticbeanstalk
  region: "us-east-2"
  app: "frontend---------------"
  env: "Frontend---------------env"
  bucket_name: "elasticbeanstalk-us-east-2-891377328480"
  bucket_path:  "frontend---------------"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"